# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nexoActualValues.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='nexoActualValues.proto',
  package='nexoPbInterface',
  syntax='proto3',
  serialized_pb=_b('\n\x16nexoActualValues.proto\x12\x0fnexoPbInterface\x1a\x1fgoogle/protobuf/timestamp.proto\"@\n\nvectorData\x12\n\n\x02\x64x\x18\x01 \x01(\x05\x12\n\n\x02\x64y\x18\x02 \x01(\x05\x12\n\n\x02\x64z\x18\x03 \x01(\x05\x12\x0e\n\x06status\x18\x04 \x01(\r\"\x8c\x01\n\x10tighteningValues\x12\x16\n\x0etightTimeStamp\x18\x01 \x01(\x01\x12\x15\n\rprogramNumber\x18\x02 \x01(\r\x12\x13\n\x0bprogramStep\x18\x03 \x01(\r\x12\x15\n\rtCycleCounter\x18\x04 \x01(\r\x12\x0e\n\x06torque\x18\x05 \x01(\x01\x12\r\n\x05\x61ngle\x18\x06 \x01(\x05\":\n\rbatteryValues\x12\x0e\n\x06status\x18\x01 \x01(\r\x12\x19\n\x11\x61vailableCapacity\x18\x02 \x01(\r\"7\n\nwlanValues\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x19\n\x11recvFieldStrength\x18\x02 \x01(\x05\"\x96\x01\n\x0c\x62uttonValues\x12@\n\tdirSwitch\x18\x01 \x01(\x0e\x32-.nexoPbInterface.buttonValues.dirSwitchStatus\x12\x14\n\x0cstartBtnPoti\x18\x02 \x01(\r\".\n\x0f\x64irSwitchStatus\x12\x08\n\x04offS\x10\x00\x12\x07\n\x03\x63wS\x10\x01\x12\x08\n\x04\x63\x63wS\x10\x02\"=\n\x0bmotorValues\x12\x18\n\x10motorTemperature\x18\x01 \x01(\x05\x12\x14\n\x0cmotorCurrent\x18\x02 \x01(\x05\"%\n\x0cidCodeValues\x12\x15\n\rscannerIDcode\x18\x01 \x01(\t\"\xb9\x03\n\tactValues\x12/\n\x0bnsTimeStamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x31\n\x0ctoolGyroVals\x18\x02 \x01(\x0b\x32\x1b.nexoPbInterface.vectorData\x12\x32\n\rtoolAccelVals\x18\x03 \x01(\x0b\x32\x1b.nexoPbInterface.vectorData\x12-\n\x06\x62utton\x18\x04 \x01(\x0b\x32\x1d.nexoPbInterface.buttonValues\x12+\n\x05motor\x18\x05 \x01(\x0b\x32\x1c.nexoPbInterface.motorValues\x12/\n\x07\x62\x61ttery\x18\x06 \x01(\x0b\x32\x1e.nexoPbInterface.batteryValues\x12-\n\x02tv\x18\x07 \x01(\x0b\x32!.nexoPbInterface.tighteningValues\x12)\n\x04wlan\x18\x08 \x01(\x0b\x32\x1b.nexoPbInterface.wlanValues\x12-\n\x06idCode\x18\t \x01(\x0b\x32\x1d.nexoPbInterface.idCodeValuesb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])



_BUTTONVALUES_DIRSWITCHSTATUS = _descriptor.EnumDescriptor(
  name='dirSwitchStatus',
  full_name='nexoPbInterface.buttonValues.dirSwitchStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='offS', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='cwS', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ccwS', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=507,
  serialized_end=553,
)
_sym_db.RegisterEnumDescriptor(_BUTTONVALUES_DIRSWITCHSTATUS)


_VECTORDATA = _descriptor.Descriptor(
  name='vectorData',
  full_name='nexoPbInterface.vectorData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dx', full_name='nexoPbInterface.vectorData.dx', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dy', full_name='nexoPbInterface.vectorData.dy', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dz', full_name='nexoPbInterface.vectorData.dz', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='nexoPbInterface.vectorData.status', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=140,
)


_TIGHTENINGVALUES = _descriptor.Descriptor(
  name='tighteningValues',
  full_name='nexoPbInterface.tighteningValues',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tightTimeStamp', full_name='nexoPbInterface.tighteningValues.tightTimeStamp', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='programNumber', full_name='nexoPbInterface.tighteningValues.programNumber', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='programStep', full_name='nexoPbInterface.tighteningValues.programStep', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tCycleCounter', full_name='nexoPbInterface.tighteningValues.tCycleCounter', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='torque', full_name='nexoPbInterface.tighteningValues.torque', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='angle', full_name='nexoPbInterface.tighteningValues.angle', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=143,
  serialized_end=283,
)


_BATTERYVALUES = _descriptor.Descriptor(
  name='batteryValues',
  full_name='nexoPbInterface.batteryValues',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='nexoPbInterface.batteryValues.status', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='availableCapacity', full_name='nexoPbInterface.batteryValues.availableCapacity', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=285,
  serialized_end=343,
)


_WLANVALUES = _descriptor.Descriptor(
  name='wlanValues',
  full_name='nexoPbInterface.wlanValues',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='nexoPbInterface.wlanValues.status', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='recvFieldStrength', full_name='nexoPbInterface.wlanValues.recvFieldStrength', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=345,
  serialized_end=400,
)


_BUTTONVALUES = _descriptor.Descriptor(
  name='buttonValues',
  full_name='nexoPbInterface.buttonValues',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dirSwitch', full_name='nexoPbInterface.buttonValues.dirSwitch', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='startBtnPoti', full_name='nexoPbInterface.buttonValues.startBtnPoti', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _BUTTONVALUES_DIRSWITCHSTATUS,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=403,
  serialized_end=553,
)


_MOTORVALUES = _descriptor.Descriptor(
  name='motorValues',
  full_name='nexoPbInterface.motorValues',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='motorTemperature', full_name='nexoPbInterface.motorValues.motorTemperature', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='motorCurrent', full_name='nexoPbInterface.motorValues.motorCurrent', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=555,
  serialized_end=616,
)


_IDCODEVALUES = _descriptor.Descriptor(
  name='idCodeValues',
  full_name='nexoPbInterface.idCodeValues',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='scannerIDcode', full_name='nexoPbInterface.idCodeValues.scannerIDcode', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=618,
  serialized_end=655,
)


_ACTVALUES = _descriptor.Descriptor(
  name='actValues',
  full_name='nexoPbInterface.actValues',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nsTimeStamp', full_name='nexoPbInterface.actValues.nsTimeStamp', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='toolGyroVals', full_name='nexoPbInterface.actValues.toolGyroVals', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='toolAccelVals', full_name='nexoPbInterface.actValues.toolAccelVals', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='button', full_name='nexoPbInterface.actValues.button', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='motor', full_name='nexoPbInterface.actValues.motor', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='battery', full_name='nexoPbInterface.actValues.battery', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tv', full_name='nexoPbInterface.actValues.tv', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='wlan', full_name='nexoPbInterface.actValues.wlan', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='idCode', full_name='nexoPbInterface.actValues.idCode', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=658,
  serialized_end=1099,
)

_BUTTONVALUES.fields_by_name['dirSwitch'].enum_type = _BUTTONVALUES_DIRSWITCHSTATUS
_BUTTONVALUES_DIRSWITCHSTATUS.containing_type = _BUTTONVALUES
_ACTVALUES.fields_by_name['nsTimeStamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_ACTVALUES.fields_by_name['toolGyroVals'].message_type = _VECTORDATA
_ACTVALUES.fields_by_name['toolAccelVals'].message_type = _VECTORDATA
_ACTVALUES.fields_by_name['button'].message_type = _BUTTONVALUES
_ACTVALUES.fields_by_name['motor'].message_type = _MOTORVALUES
_ACTVALUES.fields_by_name['battery'].message_type = _BATTERYVALUES
_ACTVALUES.fields_by_name['tv'].message_type = _TIGHTENINGVALUES
_ACTVALUES.fields_by_name['wlan'].message_type = _WLANVALUES
_ACTVALUES.fields_by_name['idCode'].message_type = _IDCODEVALUES
DESCRIPTOR.message_types_by_name['vectorData'] = _VECTORDATA
DESCRIPTOR.message_types_by_name['tighteningValues'] = _TIGHTENINGVALUES
DESCRIPTOR.message_types_by_name['batteryValues'] = _BATTERYVALUES
DESCRIPTOR.message_types_by_name['wlanValues'] = _WLANVALUES
DESCRIPTOR.message_types_by_name['buttonValues'] = _BUTTONVALUES
DESCRIPTOR.message_types_by_name['motorValues'] = _MOTORVALUES
DESCRIPTOR.message_types_by_name['idCodeValues'] = _IDCODEVALUES
DESCRIPTOR.message_types_by_name['actValues'] = _ACTVALUES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

vectorData = _reflection.GeneratedProtocolMessageType('vectorData', (_message.Message,), dict(
  DESCRIPTOR = _VECTORDATA,
  __module__ = 'nexoActualValues_pb2'
  # @@protoc_insertion_point(class_scope:nexoPbInterface.vectorData)
  ))
_sym_db.RegisterMessage(vectorData)

tighteningValues = _reflection.GeneratedProtocolMessageType('tighteningValues', (_message.Message,), dict(
  DESCRIPTOR = _TIGHTENINGVALUES,
  __module__ = 'nexoActualValues_pb2'
  # @@protoc_insertion_point(class_scope:nexoPbInterface.tighteningValues)
  ))
_sym_db.RegisterMessage(tighteningValues)

batteryValues = _reflection.GeneratedProtocolMessageType('batteryValues', (_message.Message,), dict(
  DESCRIPTOR = _BATTERYVALUES,
  __module__ = 'nexoActualValues_pb2'
  # @@protoc_insertion_point(class_scope:nexoPbInterface.batteryValues)
  ))
_sym_db.RegisterMessage(batteryValues)

wlanValues = _reflection.GeneratedProtocolMessageType('wlanValues', (_message.Message,), dict(
  DESCRIPTOR = _WLANVALUES,
  __module__ = 'nexoActualValues_pb2'
  # @@protoc_insertion_point(class_scope:nexoPbInterface.wlanValues)
  ))
_sym_db.RegisterMessage(wlanValues)

buttonValues = _reflection.GeneratedProtocolMessageType('buttonValues', (_message.Message,), dict(
  DESCRIPTOR = _BUTTONVALUES,
  __module__ = 'nexoActualValues_pb2'
  # @@protoc_insertion_point(class_scope:nexoPbInterface.buttonValues)
  ))
_sym_db.RegisterMessage(buttonValues)

motorValues = _reflection.GeneratedProtocolMessageType('motorValues', (_message.Message,), dict(
  DESCRIPTOR = _MOTORVALUES,
  __module__ = 'nexoActualValues_pb2'
  # @@protoc_insertion_point(class_scope:nexoPbInterface.motorValues)
  ))
_sym_db.RegisterMessage(motorValues)

idCodeValues = _reflection.GeneratedProtocolMessageType('idCodeValues', (_message.Message,), dict(
  DESCRIPTOR = _IDCODEVALUES,
  __module__ = 'nexoActualValues_pb2'
  # @@protoc_insertion_point(class_scope:nexoPbInterface.idCodeValues)
  ))
_sym_db.RegisterMessage(idCodeValues)

actValues = _reflection.GeneratedProtocolMessageType('actValues', (_message.Message,), dict(
  DESCRIPTOR = _ACTVALUES,
  __module__ = 'nexoActualValues_pb2'
  # @@protoc_insertion_point(class_scope:nexoPbInterface.actValues)
  ))
_sym_db.RegisterMessage(actValues)


# @@protoc_insertion_point(module_scope)
